version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 0 ## disables dependabot

  - package-ecosystem: "npm"
    directory: "/telegram-bot"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 0 ## disables dependabot
