# Default values for webapp-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# serviceName:
servicePort: 80

# host:
certResolver: letsencrypt

extraFiles: []
# - path: robots.txt
#   content: |-
#     User-agent: *
#     Allow: /
