---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: telegram-bot
  namespace: city4people-wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: main
          image: docker.pkg.github.com/kachkaev/city4people-wiki/city4people_wiki_bot:v2020092309
          imagePullPolicy: IfNotPresent
          env:
            - name: TELEGRAM_BOT_DOMAIN
              value: city4pe  ople-wiki.ru
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-token
                  key: value
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 200Mi
