apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "telegram-bot.labels" . | indent 4 }}
  name: {{ template "telegram-bot.fullname" . }}-secret
data:
  botToken: {{ .Values.botToken | b64enc | quote }}
