---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp-ingress.extrafiles" . }}
  labels:
    {{- include "webapp-ingress.labels" . | nindent 4 }}
data:
  {{ (index .Values.extraFiles 0).path }}: |-
    {{- (index .Values.extraFiles 0).content | nindent 4 }}
