apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-ingress.extrafiles" . }}
  labels:
    {{- include "webapp-ingress.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webapp-ingress.selectorLabels" . | nindent 4 }}
