name: Produce Docker images
on:
  release:
    types: [created]
jobs:
  containerize_telegram-bot:
    name: Containerize the Telegram Bot
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run containerize script
        run: yarn workspace telegram-bot containerize

      - name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

      - name: Push image
        run: |
          export CONTAINER_IMAGE=docker.pkg.github.com/${{ github.repository }}/telegram-bot:${{ github.event.release.tag_name }}
          docker tag telegram-bot:local "${CONTAINER_IMAGE}"
          docker push "${CONTAINER_IMAGE}"
